### ISSUE TITLE
Why not use the CloudEvents SDK to parse events?

### ISSUE THREAD

**Issue by friism** [meteatamel/knative-tutorial#1]
I'm curious why the [translation example](https://github.com/meteatamel/knative-tutorial/blob/master/docs/07-translationeventing.md) doesn't use the [CloudEvents SDK](https://github.com/cloudevents/sdk-csharp)?

**Comment by meteatamel** [comment]
I tried to use it but it wasn't ready for ASP.NET Core 2.1 version I was using initially. I contacted the maintainer and he confirmed that was the case. I'm open to PRs if you have this working.

**Comment by meteatamel** [comment]
I changed translation and vision samples to use CloudEvents SDK now. Thanks for raising this.
