### ISSUE TITLE
I can not get the helloworld-python on.

### ISSUE THREAD

**Issue by dongwangdw** [meteatamel/knative-tutorial#10]
I followed the doc, and went through this process.

Everything is OK and the pod can persist for sometime and will go away.
I am not sure if this is something wrong. But I found every is good. I think it is because not workload.

The hostname url is `http://helloworld-python.default.example.com`. I got this with cmd `kubectl get ksvc helloworld-python  --output=custom-columns=NAME:.metadata.name,URL:.status.url`

but when I try to `curl -H "Host: helloworld-python.default.example.com" http://$EXTERNAL_IP`

it always complains that `could not be resolved by DNS.` I can not debug the cause. 

Please help. Thanks.

**Comment by meteatamel** [comment]
Are you sure you deployed the right yaml file? Because our instructions have "helloworld" instead of "helloworld-python" for service name.

**Comment by dongwangdw** [comment]
yes, I found this difference. I deployed the right one. The pod could be started. a minutes later it will be autoscaled to zero. 

How can I debug it?

`kubectl get all -n default`
`deployment.apps/helloworld-python-9sdh7-deployment   0/0     0            0           4m1s`
and others are all ready.

`kubectl get svc istio-ingressgateway -n istio-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}' ` will output the right external IP.

`k get ksvc helloworld-python  --output=custom-columns=NAME:.metadata.name,URL:.status.url`
outputs the `http://helloworld-python.default.example.com`

then `curl -H "Host: helloworld-python.default.example.com" http://$IP` and it would give the DNS error.

**Comment by dongwangdw** [comment]
```* Rebuilt URL to: xxx.xxx.xxx.xxx/
*   Trying xxx.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to xxx.xxx.xxx.xxx (xxx.xxx.xxx.xxx) port 80 (#0)
> GET / HTTP/1.1
> Host: helloworld-python.default.example.com
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Type: text/html; charset=utf-8
< Connection: Keep-Alive
< Content-Length: 576
<
<HTML><HEAD>
<TITLE>Network Error</TITLE>```

Part of the log, I replaced the IP with xxx.

**Comment by meteatamel** [comment]
I just tested the python sample and it worked for me. Not sure what's different in your case.

**Comment by meteatamel** [comment]
I'm closing this. Please re-open again if you still have issues.
