### ISSUE TITLE
I was not able to reach my app (error 404)

### ISSUE THREAD

**Issue by kondalaraogangavarapu** [meteatamel/knative-tutorial#16]
curl --header "Host:http://cool-app.default.example.com" 34.x.x.x -v

I followed the exact steps in knative tutorial to create a cluster on GKE with istio and install knative, I am not able to reach my cool-app from out side of the cluster.

Can you please suggest if I am missing something?, seems like this problem is familiar among knative community. Thanks in advance

**Comment by meteatamel** [comment]
We solved this issue on Slack, so closing it.
