### ISSUE TITLE
Kaniko Build Template failed

### ISSUE THREAD

**Issue by AllenRay** [meteatamel/knative-tutorial#4]
knative 0.5.2
run command : kubectl apply -f https://raw.githubusercontent.com/knative/build-templates/master/kaniko/kaniko.yaml 

response: 
error: unable to recognize "https://raw.githubusercontent.com/knative/build-templates/master/kaniko/kaniko.yaml": no matches for kind "BuildTemplate" in version "build.knative.dev/v1alpha1" 

how to fix it?
it's knative version is old?

**Comment by meteatamel** [comment]
I tested with Kaniko 0.6 and it works as expected. Please re-open if you still see an issue.
