### ISSUE TITLE
thorough workload identity tutorial setup of KNative-GCP

### ISSUE THREAD

**Issue by ethai** [meteatamel/knative-tutorial#47]
Hi Mete, can you provide a more thorough of setting up the knative-gcp installation with the focus on leveraging workload identity setup for the control plan.

Additionally the explicit data plane setup with workload identity is confusing as i don't get why it would be required to provide the spec.googleServiceAccount in the manifest.
https://github.com/google/knative-gcp/blob/master/docs/install/pubsub-service-account.md

** I did log an issue under the knative-gcp and Grace had mentioned this wasn't supported prior to 0.14.0 so i was eager to try when it was recently released.  Hopefully you have better luck.

the annotated service account that would say run the data plane CloudPubSubSource for example should automagically be authorized and authenticated to use whatever google apis it's entitled to.

**Comment by ethai** [comment]
@meteatamel  any luck in validating to take advantage of workload identity in using KNative-GCP CRDs?

**Comment by meteatamel** [comment]
Unfortunately, I couldn't get to this yet. I'm hoping early next week.

**Comment by ethai** [comment]
Sure thing, the steps are pretty minimal for me to not get this so I can honestly only assume the release 0.14.0 itself is not liking workload identity configuration.   The state of my unsuccessful install to summarize is knative-gcp's control plane controller refusing to start up which again i've concluded is due to the authentication/authorization setup of either workload ident or secrets

**Comment by meteatamel** [comment]
I tested this out today and you're right. I couldn't get CloudPubSubSource to get into ready state. I updated my setup scripts to also work on workload identity in case you want to take a look. I'll dig further and reach out to one of Knative engineers to see if they have any idea what might be wrong.

**Comment by ethai** [comment]
so you're able to get the main control plane to leverage workload identity - from my test it's stuck on ContainerCreating status.  I never even got around to using a event source yet.  I did log this issue and Grace had mention to not use the release version just yet, but based on the release note of 0.14.0 i was expecting it to work.

https://github.com/google/knative-gcp/issues/787

**Comment by meteatamel** [comment]
Yeah I got the CloudPubSubSource created but it never gets into READY state and it doesn't what's wrong either

**Comment by meteatamel** [comment]
Ok, I figured it out. Turns out, the latest Knative-GCP v0.14.0 only supports Workload identity in data plane and not control plane. You can either: 

1. run `init_control_plane.sh` to configure Secret for Controller Plane (you can still use Workload Identity with that yaml for your cloudpubsubsource in the Data Plane)
2. OR ko apply -f /github.com/google/knative-gcp/blob/master/config/ to deploy the latest controller (It supports Workload Identity for the Control Plane)

In cloudpubsubsource-workload.yaml, I also updated the service account to use cre-pubsub, instead of cloud-run-events that are used only for control plane.

**Comment by ethai** [comment]
That makes complete sense and thanks for your help validating I will try again with the non release version.

**Comment by meteatamel** [comment]
I'll close this. Please re-open if you still have the issue.
