### ISSUE TITLE
permissions issue with Vision API

### ISSUE THREAD

**Issue by gbvikas** [meteatamel/knative-tutorial#48]
Hi Mete,

With Vision API, I get below error in pod logs instead of description. Is it related some permissions?

info: vision.Startup[0]
      Storage url: gs://<STORAGE_BUCKET>/beach.jpg
fail: vision.Startup[0]
      Something went wrong: Error opening file: gs://<STORAGE_BUCKET>/beach.jpg.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/ HTTP: POST'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 908.7609ms 200

**Comment by meteatamel** [comment]
Are you replacing STORAGE_BUCKET with the real bucket id? Also, is the bucket public?

**Comment by gbvikas** [comment]
Yes Mete. I verified the bucket ID and the permissions. 

One more important point I noticed is the pub/sub messages are base64 encoded. Is that something which would impact?

Below the message I received when I followed instructions provided at: https://github.com/meteatamel/knative-tutorial/blob/master/docs/pubsubeventing.md


kubectl logs --follow event-display-<POD-NAME> -c user-container 
info: event_display.Startup[0]
      Event Display is starting...
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://0.0.0.0:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://event-display.default.svc.cluster.local/ application/json 174
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/ HTTP: POST'
info: event_display.Startup[0]
      Event Display received event: {"subscription":"cre-pull-<ID>","message":{"messageId":"1143529206453056","data":"SGVsbG8gV29ybGQ=","publishTime":"2020-04-22T06:48:12.467Z"}}
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/ HTTP: POST'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 35.8679ms 200

**Comment by meteatamel** [comment]
Yes, the message body is base64 encoded but the code for Vision API needs the attributes of bucketId and objectId to figure out where the picture is. It still looks to me that the bucket is either not public or maybe the Vision API is not enabled..

**Comment by meteatamel** [comment]
Closing it, as I didn't hear back. Please re-open if you still encounter the issue.
