### ISSUE TITLE
Update to new GCP CloudEvent types for 0.16

### ISSUE THREAD

**Issue by grantr** [meteatamel/knative-tutorial#73]
In 0.16, knative-gcp will use new CloudEvent attributes and data schemas for all types emitted by GCP sources. See https://github.com/google/knative-gcp/pull/1340 and https://github.com/googleapis/google-cloudevents.

**Comment by meteatamel** [comment]
Hi @grantr, where do I need to change these? Does this only come up in trigger definitions?

**Comment by meteatamel** [comment]
Ok, I figured out..It looks like Google Cloud related event filters need to change in triggers. I'll make the update. Thanks a lot for letting me know!

**Comment by meteatamel** [comment]
Fixed
