### ISSUE TITLE
Script for Istio Installation is broken

### ISSUE THREAD

**Issue by gaj-satha** [meteatamel/knative-tutorial#81]
In the setup folder, I first created the gke cluster by the script ./create-gke-cluster and it worked fine. Then I went ahead to install istio using the script ./install-istio and I get the following error:

```
# Install Istio CRDs
kubectl apply -f "https://raw.githubusercontent.com/knative/serving/master/third_party/istio-${ISTIO_VERSION}/istio-crds.yaml"
error: unable to read URL "https://raw.githubusercontent.com/knative/serving/master/third_party/istio-1.5.7/istio-crds.yaml", server reported 404 Not Found, status code=404

# Install Istio
kubectl apply -f "https://raw.githubusercontent.com/knative/serving/master/third_party/istio-${ISTIO_VERSION}/istio-minimal.yaml"
error: unable to read URL "https://raw.githubusercontent.com/knative/serving/master/third_party/istio-1.5.7/istio-minimal.yaml", server reported 404 Not Found, status code=404

# Check all Istio pods have STATUS 'Running'
kubectl get pods -n istio-system
No resources found in istio-system namespace.
```

When you look at the error message, it is expecting some files in folder istio-ISTIO_VERSION at [this](https://github.com/knative/serving/tree/master/third_party) location but no such folder is present. They probably are moved somewhere else. 

This needs to be resolved!

**Comment by meteatamel** [comment]
Hi, I updated the setup instructions for Knative v0.18.0. Basically, you need to install Istio with an external script now. Please check out and let me know if you have questions.
