### ISSUE TITLE
Knative trigger status not ready due to TopicReady unknown

### ISSUE THREAD

**Issue by Uvindu96** [meteatamel/knative-tutorial#84]
Recently I'm trying out the Knative sample https://github.com/meteatamel/knative-tutorial/blob/master/docs/image-processing-pipeline.md, I have created trigger with the default broker(MTChannelBasedBroker), that you mentioned in the steps. also, i have installed the Google Cloud Pub/Sub Channel in the same namespace. But I'm getting the following error from the filter trigger only other triggers are fine and they are in ready status.
![Screenshot from 2020-12-21 21-56-10](https://user-images.githubusercontent.com/31029812/102884466-a54cc180-4477-11eb-8ddb-aede51c56b76.png)

Knative version - v18.0

**Comment by Uvindu96** [comment]
@meteatamel any idea on this?

**Comment by meteatamel** [comment]
Not sure. Does this work? https://github.com/meteatamel/knative-tutorial/blob/master/docs/storageeventing.md

**Comment by Uvindu96** [comment]
@meteatamel Thank you for the response, yes I tried that sample also, I got the same issue with the trigger, looks like the trigger is not getting ready due to the same reason, I'm trying out in Knative v18

![Screenshot from 2020-12-28 19-51-55](https://user-images.githubusercontent.com/31029812/103220585-9d44c400-4946-11eb-9c90-6bfad106dbcc.png)

**Comment by Uvindu96** [comment]
I think this issue is similar to this https://github.com/google/knative-gcp/issues/1583

**Comment by meteatamel** [comment]
I'm not sure what the problem might be. I tested this sample with Knative v0.19.0 and my instructions and it worked fine. Maybe start with a fresh cluster and Knative v0.19.0?

**Comment by Uvindu96** [comment]
@meteatamel  finally it worked, I used the setup config file (https://github.com/meteatamel/knative-tutorial/tree/master/setup) you used to setup Knative, Actually, It was easy to use that config file it helped me a lot, Thank you for pay attention to this matter..!

**Comment by meteatamel** [comment]
Good to know that it worked. Closing the issue then.
